// copy the en-GB content as default content, and make sure to remove the `<base>` tag from the index
var fs = require("fs-extra");
fs.copySync("en-GB/index.html", "index.html");
fs.copySync("en-GB/article.js", "article.js");
var html = fs.readFileSync("index.html").toString();
html = html.replace('    <base href="..">', '');
html = html.replace('className=', 'class=');
html = "<!-- AUTOGENERATED CONTENT, PLEASE EDIT 'index.template.html' INSTEAD! -->\n" + html;
fs.writeFileSync("index.html", html);
